BOARD_SIZE = 6
CELL_SIZE = 80

HEADER_HEIGHT = 80
WINDOW_WIDTH = BOARD_SIZE * CELL_SIZE
WINDOW_HEIGHT = BOARD_SIZE * CELL_SIZE + HEADER_HEIGHT

FPS = 60

GREEN = (34, 139, 34)
GRID_COLOR = (0, 0, 0)

BLACK = 1
WHITE = 2